context:
  name: rattler-index
  version: "0.27.16"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/conda/rattler/archive/rattler_index-v${{ version }}.tar.gz
  sha256: 6fce69b0135102e821014dc806153efdcec3be0c435d26220a747964ac509f26

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - export OPENSSL_DIR=$PREFIX
      - cd crates/rattler_index
      - cargo-bundle-licenses --format yaml --output ../../THIRDPARTY.yml
      # s3 feature requires rustls which (as of reqwest 0.12) requires ring which is only compatible with clang
      # xref https://github.com/conda/rattler/pull/2033
      - cargo auditable install --no-track --locked --features native-tls,rattler_config${{ ',s3' if target_platform != 'win-arm64' else '' }} --no-default-features --root ${{ PREFIX }} --path .

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable
  host:
    - openssl
    - libiconv

tests:
  - script:
      - rattler-index --version
  - package_contents:
      bin:
        - rattler-index
      strict: true

about:
  homepage: https://github.com/conda/rattler
  documentation: https://docs.rs/rattler_index/latest/rattler_index
  summary: Index conda channels using rattler
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/conda/rattler/tree/main/crates/rattler_index

extra:
  recipe-maintainers:
    - delsner
    - pavelzw
    - wolfv
