context:
  name: rattler-index
  version: "0.21.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/conda/rattler/archive/rattler_index-v${{ version }}.tar.gz
  sha256: e7707284dcc448b02c5a9355028b3c23b755be8b8667c5d696cfceed8042680e

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - openssl
    - libiconv

tests:
  - script:
      - rattler-index --version

about:
  homepage: https://github.com/conda/rattler
  documentation: https://docs.rs/rattler_index/latest/rattler_index
  summary: Index conda channels using rattler
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/conda/rattler/tree/main/crates/rattler_index

extra:
  recipe-maintainers:
    - pavelzw
