context:
  name: rattler-index
  version: "0.23.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/conda/rattler/archive/rattler_index-v${{ version }}.tar.gz
  sha256: d6a3e7014a115551e9ba55247446c5b4b3d3edb748766cc225f377075c5543f0

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - openssl
    - libiconv

tests:
  - script:
      - rattler-index --version

about:
  homepage: https://github.com/conda/rattler
  documentation: https://docs.rs/rattler_index/latest/rattler_index
  summary: Index conda channels using rattler
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/conda/rattler/tree/main/crates/rattler_index

extra:
  recipe-maintainers:
    - delsner
    - pavelzw
